version: '3.8'

services:
  postgres:
    image: postgres
    container_name: customer
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5439:5432'
    networks:
      - default

volumes:
  postgres:

networks:
  default:
    driver: bridge
