server:
  port: 8080
spring:
  application:
    name: Customer_Service
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        exclude: '*'
logging:
  level:
    root: info
    web: info
